### ISSUE TITLE
Fizz Buzz implementation in Java

### ISSUE THREAD

**Issue by ashish-r** [ashish-r/Fizz-Buzz#11]
Fizz Buzz implementation in java

**Comment by lorenzoverardo** [comment]
I can do this

**Comment by shubhamnag14** [comment]
i'd like to solve this problem..so can i

**Comment by ashish-r** [comment]
Yes sure.

**Comment by ashish-r** [comment]
@shubhamnag14  Every contribution is appreciated. You can submit your solution. Happy Hacking! :)
