### ISSUE TITLE
Fizz Buzz implementation in Rust.

### ISSUE THREAD

**Issue by ashish-r** [ashish-r/Fizz-Buzz#12]
Contribute your Fizz Buzz implementation in Rust.

**Comment by ashwanijha04** [comment]
I want to work on it. Please assign it to me

**Comment by ashish-r** [comment]
@ashwanijha04 Assigned. Happy Hacking! 👍🏻

**Comment by ashwanijha04** [comment]
Thanks 👍

**Comment by ashwanijha04** [comment]
Added PR -> https://github.com/ashish-r/Fizz-Buzz/pull/75
