### ISSUE TITLE
Add fizz buzz program in your favourite programming language

### ISSUE THREAD

**Issue by ashish-r** [ashish-r/Fizz-Buzz#3]
Every contribution is appreciated.

**Comment by ani-coder-hacker** [comment]
I'll do this in C++

**Comment by ani-coder-hacker** [comment]
> I'll do this in C++

Yeah it turns out that that the C++ one is already done so yeah

**Comment by ashish-r** [comment]
@ani-coder-hacker  You can try with a different approach and raise your PR.

**Comment by shubhamnag14** [comment]
can i contribute fizz buzz program in python...if yes 
please assign me this issue

**Comment by opentechnologist** [comment]
hi, my daughter (through my account) would like to contribute
by doing a **standard pascal** implementation of **fizzbuzz**.
if you agree, please assign a new _fizzbuzz-pascal issue_ to me. thank you! 😁
