### ISSUE TITLE
Fizz Buzz implementation in TypeScript

### ISSUE THREAD

**Issue by ashish-r** [ashish-r/Fizz-Buzz#33]
Raise Your PR for Fizz Buzz implementation in TypeScript

**Comment by thisavijit** [comment]
@ashish-r  Please assign it to me

**Comment by ashish-r** [comment]
@adavijit Assigned. Happy Hacking! :)

**Comment by thisavijit** [comment]
@ashish-r  done! https://github.com/ashish-r/Fizz-Buzz/pull/110 check it
