### ISSUE TITLE
Fizz Buzz implementation in Python

### ISSUE THREAD

**Issue by ashish-r** [ashish-r/Fizz-Buzz#35]
Raise your PR for FizzBuzz implementation in Python

**Comment by amoghatsunil** [comment]
@ashish-r I would like to work on this issue

**Comment by SMITVASOYA** [comment]
I really want to contribute to it...

**Comment by SMITVASOYA** [comment]
can I?

**Comment by ashish-r** [comment]
@amoghatsunil @SMITVASOYA  Every contribution is appreciated. Happy Hacking! :)

P.S.: Add your solution in a new file to avoid overwriting the existing solutions.

**Comment by Esoiya** [comment]
Can I work on this issue too @ashish-r ?

**Comment by ashish-r** [comment]
@Esoiya Sure. Most Welcome. 👍🏻

**Comment by shrutkas78** [comment]
Can I contribute to this issue?

**Comment by amoghatsunil** [comment]
@ashish-r Can you please add hacktoberfest topic and label "hacktoberfest-accepted" to my pr

**Comment by amankumar00** [comment]
Hi, can I contribute to this issue?

**Comment by prabhat34** [comment]
I would like to work on this issue, can you please assign it to me?
