### ISSUE TITLE
Fizz Buzz implementation in PHP

### ISSUE THREAD

**Issue by ashish-r** [ashish-r/Fizz-Buzz#36]
Raise your PR for Fizz Buzz implementation in PHP

**Comment by thisavijit** [comment]
@ashish-r  Please assign it to me

**Comment by ashish-r** [comment]
@adavijit Assigned. Happy Hacking! :)

**Comment by thisavijit** [comment]
@ashish-r  https://github.com/ashish-r/Fizz-Buzz/pull/125 done. Check this one

**Comment by thisavijit** [comment]
@ashish-r  Merge it

**Comment by sebabratakundu** [comment]
Hello @ashish-r , I did the FizzBuzz in php using the OOPs concept. please review my PR. Happy Hacktoberfest :)
#134
