### ISSUE TITLE
Welcome to Hackertoberfest 2020!

### ISSUE THREAD

**Issue by ashish-r** [ashish-r/Fizz-Buzz#4]
It’s that time of year again when we come together to support and celebrate the open source technologies we use and love. To help you celebrate Hacktoberfest 2020, I am opening this issue for first-time open source contributors. 
If this is your first contribution and you need any help, or if you are facing any issue, comment below.

**Comment by Kswierk** [comment]
Hello, can I help?

**Comment by ashish-r** [comment]
@Kswierk every contribution is appreciated.

**Comment by sebabratakundu** [comment]
how can I contribute?
