### ISSUE TITLE
Fizz Buzz implementation in C#

### ISSUE THREAD

**Issue by ashish-r** [ashish-r/Fizz-Buzz#41]
Raise your PR for Fizz Buzz implementation in C#

**Comment by AndreiG23** [comment]
Can I do it?

**Comment by ashish-r** [comment]
Yes, every contribution is appreciated.

**Comment by AndreiG23** [comment]
nvm C# is already done

**Comment by ashish-r** [comment]
If you want, you can share your PR with a different implementation. 😊

**Comment by AndreiG23** [comment]
I think I found another way to implement it. Check the PR!
