### ISSUE TITLE
Fizz Buzz implementation in GO

### ISSUE THREAD

**Issue by ashish-r** [ashish-r/Fizz-Buzz#47]
Raise your PR for Fizz Buzz implementation in GO

**Comment by Aashishkushwaha** [comment]
I want to take this up can you please assign this me.

**Comment by ashish-r** [comment]
@Aashishkushwaha Assigned. Happy Hacking. 👍🏻

**Comment by mjavier2k** [comment]
I'd like to give this a try too

**Comment by ashish-r** [comment]
Assigned :)
