### ISSUE TITLE
Fizz Buzz implementation in Elixir

### ISSUE THREAD

**Issue by ashish-r** [ashish-r/Fizz-Buzz#54]
Raise your PR for Fizz Buzz implementation in Elixir

**Comment by nakennedy11** [comment]
I'd like to take this please :)

**Comment by nakennedy11** [comment]
nevermind, I see an implementation has been merged already

**Comment by ashish-r** [comment]
@nakennedy11 
 If you want, you can share your PR with a different implementation. 😊
