### ISSUE TITLE
Fizz Buzz implementation in c

### ISSUE THREAD

**Issue by ashish-r** [ashish-r/Fizz-Buzz#9]
Create PRs for Fizz Buzz implementation in c.

**Comment by akankshast** [comment]
Hi, I would like to contribute to this. Could you please assign it to me
Regards,
Akanksha

**Comment by ashish-r** [comment]
Yes sure.

**Comment by ashish-r** [comment]
@akankshast Assigned. Happy Hacking! :)

**Comment by oldflame** [comment]
Hey, can you assign this to me please? Would love to work on this one

**Comment by ashish-r** [comment]
Assigned. Happy Hacking. 👍🏻

**Comment by prabhat34** [comment]
can you please assign this issue to me?
